resourcestring                                     {deutsch}

  captsFC='Demo: Steuerung einer C23/E90';
  capBootTime='Zeit seit Boot';
  hntBootTime='Zeit seit Booten des Systems';
  capPort='USB ports suchen...';
  hntPort='Im Falle von Verbindungsproblemen USB-Kabel ziehen und Stecken.'+lineending+
          'Doppelklick um Portliste zu erneuern.';
  capConnect='Verbinden';
  hntConnect='Mit dem ausgewählten USB-Port verbinden';
  capDisConnect='Trennen';
  hntDisConnect='System vom USB-Port trennen';
  hntSpeed='Baudrate einstellen. Default 115200 sollte für Kopter und Kamera gleichermaßen funktionieren.';
  capRecord='CSV aufzeichnen';
  hntRecord='Aufzeichnen der empfangenen Daten-Messages in eine CSV Datei als Hexadezimal Zahlen';
  capCenter='Mitte';
  hntCenter='Setze zurück in neutrale Position (Mittelstellung)';
  hntTiltControl='Kamera neigen';
  hntTiltMode='Tilt mode: Angle / Velocity';
  hntPanMode='Pan mode: Follow / Pan controllable / Global';
  hntPanControl='Kamera drehen';
  capClose='Beenden';
  hntClose='Programm beenden';
  hntStatusBar='Anzahl gesendeter Messages | Anzahl empfangener Messages received | Status';
  rsSaved=' gespeichert';
  rsDisconnected='Getrennt';
  rsConnected='Verbunden';
  rsTime='Zeit';
  rsValue='Wert';
  errNoUSBport='Kein USB-Port verfügbar';

