resourcestring                                     {english}

  captsFC='Act as flight controller to C23/E90 (Demo)';
  capBootTime='Time since boot';
  hntBootTime='Time since boot of the device';
  capPort='Scan USB ports...';
  hntPort='In case of connection Problems unplug and plug USB cable.'+lineending+
          'Double click to update port list.';
  capConnect='Connect';
  hntConnect='Connect to selected USB port';
  capDisConnect='Disconnect';
  hntDisConnect='Disonnect UART from USB port';
  hntSpeed='Select baud rate. Default 115200 shoult work for drone and camera.';
  capRecord='Record CSV';
  hntRecord='Record the received data messages to a CSV file in hexa-decimal format';
  capCenter='Center';
  hntCenter='Set to neutral position';
  hntTiltControl='Camera tilt';
  hntTiltMode='Tilt mode: Angle / Velocity';
  hntPanMode='Pan mode: Follow / Pan controllable / Global';
  hntPanControl='Pan control';
  capClose='Close';
  hntClose='Disconnect and quit';
  hntStatusBar='Number messages sent | Number messages received | Status';
  rsSaved=' saved';
  rsDisconnected='Disconnected';
  rsConnected='Connected';
  rsTime='Time';
  errNoUSBport='No USB port available';

